/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import Model.CustoE;
import Controller.CustoEDAO;

/**
 *
 * @author Max
 */
public final class CustosExtras extends javax.swing.JInternalFrame {

    String modoCustoE;

    /**
     * Creates new form CustosExtras
     */
    public CustosExtras() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tbl_cust_ex.getModel();
        tbl_cust_ex.setRowSorter(new TableRowSorter(modelo));

        //Recarregar a lista criada
        readCustosExtras();

        modoCustoE = "Navegar";
        ManipulaInterfaceCustoE();
    }

    public void readCustosExtras() {
        DefaultTableModel modelo = (DefaultTableModel) tbl_cust_ex.getModel();
        //Para que não duplique os valores ao inserir
        modelo.setNumRows(0);
        //Criando o objeto DAO para ser passado na nossa Jtabel
        CustoEDAO fdao = new CustoEDAO();

        //Ira pegar os valores que estão na lista e passando para o objeto
        for (CustoE f : fdao.read()) {
            modelo.addRow(new Object[]{
                //Vao pegar os valores que estão no banco
                f.getId(),
                f.getData(),
                f.getNome(),
                f.getQtd(),
                f.getPreco()
            });
        }
    }

    public void ManipulaInterfaceCustoE() { //Manipulaçao da Tabela
//        Modo de operaçao dos botoes utilizados no projeto
        switch (modoCustoE) {

            case "Navegar":     //Somente o botao novo ira estar disponivel
                btn_cust_salvar.setEnabled(false);
                btn_cust_cancelar.setEnabled(false);
                c_cust_preco.setEnabled(false);
                c_cust_data.setEnabled(false);
                c_cust_qtd.setEnabled(false);
                c_cust_nome.setEnabled(false);
                btn_cust_novo.setEnabled(true);
                btn_cust_editar.setEnabled(false);
                btn_cust_excluir.setEnabled(false);
                break;

            case "Novo":    //Quando Apertado o botao Novo ira liberar os campos para o cadastro

                btn_cust_salvar.setEnabled(true);
                btn_cust_cancelar.setEnabled(true);
                c_cust_preco.setEnabled(true);
                c_cust_data.setEnabled(true);
                c_cust_qtd.setEnabled(true);
                c_cust_nome.setEnabled(true);
                btn_cust_novo.setEnabled(false);
                btn_cust_editar.setEnabled(false);
                btn_cust_excluir.setEnabled(false);
                break;

            case "Editar":
                btn_cust_salvar.setEnabled(true);
                btn_cust_cancelar.setEnabled(true);
                c_cust_preco.setEnabled(true);
                c_cust_data.setEnabled(true);
                c_cust_qtd.setEnabled(true);
                c_cust_nome.setEnabled(true);
                btn_cust_novo.setEnabled(true);
                btn_cust_editar.setEnabled(false);
                btn_cust_excluir.setEnabled(false);
                break;

            case "Excluir":
                btn_cust_salvar.setEnabled(false);
                btn_cust_cancelar.setEnabled(false);
                c_cust_preco.setEnabled(false);
                c_cust_data.setEnabled(false);
                c_cust_qtd.setEnabled(false);
                c_cust_nome.setEnabled(false);
                btn_cust_novo.setEnabled(true);
                btn_cust_editar.setEnabled(false);
                btn_cust_excluir.setEnabled(false);
                break;

            case "Selecao":
                //Os botões editar e exluir estaram disponiveis para fazer a alterção da tabela
                btn_cust_salvar.setEnabled(false);
                btn_cust_cancelar.setEnabled(false);
                c_cust_data.setEnabled(false);
                c_cust_nome.setEnabled(false);
                c_cust_qtd.setEnabled(false);
                btn_cust_novo.setEnabled(false);
                btn_cust_editar.setEnabled(true);
                btn_cust_excluir.setEnabled(true);
                break;

            default:
                System.out.println("Modo Invalido");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cust_ex = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        c_cust_data = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c_cust_nome = new javax.swing.JTextField();
        btn_cust_cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        c_cust_qtd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        c_cust_preco = new javax.swing.JTextField();
        btn_cust_salvar = new javax.swing.JButton();
        btn_cust_novo = new javax.swing.JButton();
        btn_cust_editar = new javax.swing.JButton();
        btn_cust_excluir = new javax.swing.JButton();
        cmd_print = new javax.swing.JButton();

        setClosable(true);

        tbl_cust_ex.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tbl_cust_ex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Data", "Nome", "Qtd", "Preco $"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_cust_ex.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_cust_ex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_cust_exMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_cust_ex);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Cadastro Produto"));

        jLabel1.setText("Data");

        c_cust_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cust_dataActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome :");

        c_cust_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cust_nomeActionPerformed(evt);
            }
        });

        btn_cust_cancelar.setText("Cancelar");
        btn_cust_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cust_cancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Qtd :");

        c_cust_qtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cust_qtdActionPerformed(evt);
            }
        });

        jLabel7.setText("Preço :");

        c_cust_preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cust_precoActionPerformed(evt);
            }
        });

        btn_cust_salvar.setText("Salvar");
        btn_cust_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cust_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c_cust_data, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(c_cust_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_cust_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_cust_salvar)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_cust_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btn_cust_cancelar)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(c_cust_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(c_cust_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(c_cust_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(c_cust_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cust_cancelar)
                    .addComponent(btn_cust_salvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_cust_novo.setText("Novo");
        btn_cust_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cust_novoActionPerformed(evt);
            }
        });

        btn_cust_editar.setText("Editar");
        btn_cust_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cust_editarActionPerformed(evt);
            }
        });

        btn_cust_excluir.setText("Excluir");
        btn_cust_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cust_excluirActionPerformed(evt);
            }
        });

        cmd_print.setText("Imprimir");
        cmd_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_cust_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cust_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cust_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmd_print)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cust_novo)
                    .addComponent(btn_cust_excluir)
                    .addComponent(btn_cust_editar)
                    .addComponent(cmd_print))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Custo Extra", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_cust_exMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cust_exMouseClicked
        //Se clicar em linha valida valida ele ira abrir o modo selecao
        if (tbl_cust_ex.getSelectedRow() != -1) {

            c_cust_data.setText(tbl_cust_ex.getValueAt(tbl_cust_ex.getSelectedRow(), 1).toString());
            c_cust_nome.setText(tbl_cust_ex.getValueAt(tbl_cust_ex.getSelectedRow(), 2).toString());
            c_cust_qtd.setText(tbl_cust_ex.getValueAt(tbl_cust_ex.getSelectedRow(), 3).toString());
            c_cust_preco.setText(tbl_cust_ex.getValueAt(tbl_cust_ex.getSelectedRow(), 4).toString());
            modoCustoE = "Selecao";
            ManipulaInterfaceCustoE();
        }
    }//GEN-LAST:event_tbl_cust_exMouseClicked

    private void c_cust_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cust_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cust_dataActionPerformed

    private void c_cust_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cust_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cust_nomeActionPerformed

    private void btn_cust_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cust_cancelarActionPerformed
        //Limpa os campos de inserção 
        c_cust_data.setText("");
        c_cust_nome.setText("");
        modoCustoE = "Navegar";
        ManipulaInterfaceCustoE();
    }//GEN-LAST:event_btn_cust_cancelarActionPerformed

    private void c_cust_qtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cust_qtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cust_qtdActionPerformed

    private void c_cust_precoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cust_precoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cust_precoActionPerformed

    private void btn_cust_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cust_salvarActionPerformed
        //Apos clicar em salvar ele atribui os valores digitados e adicionado na variavel E
        CustoE e = new CustoE();
        //Objeto DAO que sera inserido no banco de dados
        CustoEDAO dao = new CustoEDAO();

        if (modoCustoE.equals("Novo")) {
            /*Se for uma nova operação então ele vai pegar os dados que vão ser inseridos 
            e passar os dados para o objeto determinado */
            e.setData(c_cust_data.getText());
            e.setNome(c_cust_nome.getText());
            e.setQtd(Integer.parseInt(c_cust_qtd.getText()));
            e.setPreco(Double.parseDouble(c_cust_preco.getText()));
            dao.create(e);
        } else if (modoCustoE.equals("Editar")) {
            /*Caso a operação selecionada for "Editar" então a linha selecionada
            na tabela ira recarregar os valores para os campos para poderem ser editados*/
            e.setData(c_cust_data.getText());
            e.setNome(c_cust_nome.getText());
            e.setQtd(Integer.parseInt(c_cust_qtd.getText()));
            e.setPreco(Double.parseDouble(c_cust_preco.getText()));
            e.setId((int) tbl_cust_ex.getValueAt(tbl_cust_ex.getSelectedRow(), 0));
            dao.update(e);
        }

        readCustosExtras();
        //Limpa os campos de inserção 
        c_cust_data.setText("");
        c_cust_nome.setText("");
        c_cust_qtd.setText("");
        c_cust_preco.setText("");
        modoCustoE = "Navegar";
        ManipulaInterfaceCustoE();
    }//GEN-LAST:event_btn_cust_salvarActionPerformed

    private void btn_cust_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cust_novoActionPerformed
        //Limpa os campos de inserção 
        c_cust_data.setText("");
        c_cust_nome.setText("");
        c_cust_qtd.setText("");
        c_cust_preco.setText("");
        modoCustoE = "Novo";
        ManipulaInterfaceCustoE();
    }//GEN-LAST:event_btn_cust_novoActionPerformed

    private void btn_cust_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cust_editarActionPerformed
        modoCustoE = "Editar";
        ManipulaInterfaceCustoE();
    }//GEN-LAST:event_btn_cust_editarActionPerformed

    private void btn_cust_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cust_excluirActionPerformed
        //Tela de pergunta se realmente quer excluir a linha
        int resp = 0;
        resp = JOptionPane.showConfirmDialog(null, "Deseja Excluir ?");

        // Pega a linha selecionada e se a resposta for SIM exclui da tabela   
        if ((tbl_cust_ex.getSelectedRow() != -1) && (resp == JOptionPane.YES_OPTION)) {

            CustoE f = new CustoE();
            CustoEDAO dao = new CustoEDAO();

            f.setId((int) tbl_cust_ex.getValueAt(tbl_cust_ex.getSelectedRow(), 0));
            dao.delete(f);
            readCustosExtras();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }

        modoCustoE = "Excluir";
        ManipulaInterfaceCustoE();
    }//GEN-LAST:event_btn_cust_excluirActionPerformed

    private void cmd_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_printActionPerformed
        // Dara o Titulo do seu relatorio
        MessageFormat header = new MessageFormat("Tabela Custo Extra");
        MessageFormat footer = new MessageFormat("Page{0,number,integer }");
        try {
            //Chama a tabela seleciona e atribui o titulo
            tbl_cust_ex.print(JTable.PrintMode.NORMAL, header, footer);

        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_cmd_printActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cust_cancelar;
    private javax.swing.JButton btn_cust_editar;
    private javax.swing.JButton btn_cust_excluir;
    private javax.swing.JButton btn_cust_novo;
    private javax.swing.JButton btn_cust_salvar;
    private javax.swing.JTextField c_cust_data;
    private javax.swing.JTextField c_cust_nome;
    private javax.swing.JTextField c_cust_preco;
    private javax.swing.JTextField c_cust_qtd;
    private javax.swing.JButton cmd_print;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_cust_ex;
    // End of variables declaration//GEN-END:variables
}
